### ISSUE TITLE
docs: Hello, am trying to figure out how to use this package currently for voice notes and call streaming

### ISSUE THREAD

**Issue by jbarasa** [alnitak/flutter_recorder#11]
### Documentation Request for Recording Controls & Waveform Visualization

Hi, I'm currently implementing voice notes using `flutter_recorder` and need clarification on some core functionalities.

**Current Implementation**
I'm using:
- `recorder.setPauseRecording(pause: boolean)` for pause/resume
- `recorder.getWave()` for waveform visualization
- Recording to WAV files with custom paths

**Documentation Needed For:**

1. **Pause & Resume Recording**
   - Is `setPauseRecording(pause: boolean)` the correct approach?
   - Are there any cleanup steps needed when resuming?
   - Does pausing affect the final file output?

2. **Waveform Visualization**
   - What's the recommended polling frequency for `getWave()`?
   - What's the format of the wave data (range, number of points)?
   - Are there any performance considerations?

3. **Recording Management**
   - Best practices for file handling during pause/resume
   - Recommended approach for recording timer implementation
   - Memory management considerations for longer recordings

**Use Case Context:**
Building a voice notes feature that requires:
- Real-time waveform visualization
- Pause/Resume functionality
- Recording duration tracking
- File access for playback/deletion

### Documentation Request: Audio Configuration & Recording Features

1. **Audio Configuration**
   ```dart
   _recorder.init(
     sampleRate: 44100,
     channels: RecorderChannels.stereo,
     format: PCMFormat.f32le,
   );
   ```
   - What are the recommended configuration settings for voice recording?
   - How to configure audio context for optimal voice recording quality?
   - Can we configure similar audio settings as shown below for the recorder?
   ```dart
   // Current player configuration - need equivalent for recorder
   await setAudioContext(AudioContext(
     android: AudioContextAndroid(
       contentType: AndroidContentType.speech,
       usageType: AndroidUsageType.media,
       audioFocus: AndroidAudioFocus.none,
       audioMode: AndroidAudioMode.normal,
     ),
     iOS: AudioContextIOS(
       category: AVAudioSessionCategory.playAndRecord,
       options: {
         AVAudioSessionOptions.defaultToSpeaker,
         AVAudioSessionOptions.allowBluetooth,
         AVAudioSessionOptions.allowBluetoothA2DP,
         AVAudioSessionOptions.mixWithOthers,
       },
     ),
   ));
   ```

2. **Feature Requirements**
   - How to configure audio quality settings (bitrate, encoding)?
   - Best practices for handling bluetooth/headphone routing?
   - How to ensure optimal performance for:
     - Background recording
     - Long duration recordings
     - Pause/resume functionality

3. **Platform-Specific Considerations**
   - Are there different configurations needed for iOS vs Android?
   - How to handle audio session interruptions?
   - Best practices for permission handling?

Would greatly appreciate examples or documentation covering these scenarios. Thank you!

**Comment by alnitak** [comment]
Hi @jbarasa,

there is a lot to write, I'll try to do my best to reply.

1. **Pause & Resume Recording**
Yes, `setPauseRecording(pause: boolean)` is the correct way. There are no cleanup steps. The recording to its job writing into a file (on the web it writes into memory), so there is almost no lag when you un-pause the recording. There could be a lag at max of `samplerate / (1024 * bytesSample * channels)` milliseconds (this is almost correct I think :) ).

> Does pausing affect the final file output?
I didn't understand this. The audio data is written when recording starts and it doesn't write when you pause. When you call the stop recording, the WAV header file is updated and the file is closed.

2. **Waveform Visualization**
When you call `getWave()`, as for the `getFft()`, retrieve the current buffer data. The current data is updated every time new data comes into the buffer, so it's not certain that the data obtained from those functions is coming from the subsequent chunk of microphone audio. Could come from N audio chunks after the last call, or maybe could be the same chunk you got before if you call them really fast. That depends also on the sample rate and audio format you are using.
These methods ('getTexture2D()' and `getVolumeDb()' included) are working only when using `PCMFormat.f32le` format and return a `Float32List` with data in [-1.0, 1.0] the range.

3. **Recording Management**
Since the saved file has a WAV format (the only one supported for now), it could quickly grow in size. Take in mind that 1 second of recording stores `sampleRate * byteSample * channels` bytes per second. `f32le` and `s32le` takes 4 bytes, `s16le` 2 bytes and `s8` one. 

For a voice recording a sample rate of 22050, mono, and a format of `s16le` I think it's enough. This will store 44100 bytes per second (43 KB/s) when recording.

Currently, there is no audio context since `flutter_recorder` isn't laid around the OS audio APIs and there are no different configurations for iOS, Android or desktop, but I think that there are some other plugins that can intercept the focus for interruptions.

**Comment by jbarasa** [comment]
> Does pausing affect the final file output?
I tried playing the paused file but got an error i have to record, then stop in order to play the file
